[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
borsh = "1.5.7"
risc0-zkvm = { version = "2.0.2", default-features = false }
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3", features = ["console"] }


